colNames = {'1','2','3','4'};
rowNames = {'a','b','c','d','e','f'};
cellArr = {'a1','a2','a3','a4';...
           'b1','b2','b3','b4';...
           'c1','c2','c3','c4';...
           'd1','d2','d3','d4';...
           'e1','e2','e3','e4';...
           'f1','f2','f3','f4'};



LCA = labeledCellArr(cellArr,colNames,rowNames);